# This file was generated by GoReleaser. DO NOT EDIT.
cask "datamitsu" do
  version "0.0.17"

  on_macos do
    on_intel do
      sha256 "b371b6ea3f83d8d023915b6607b270891aafde3696891111098120545362f320"
      url "https://github.com/datamitsu/datamitsu/releases/download/v#{version}/datamitsu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b139749ca86bd27cbc75b6272dc0fbf29ff2facffe2183158f989125417ad972"
      url "https://github.com/datamitsu/datamitsu/releases/download/v#{version}/datamitsu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "06ea732b6c237ae38f816361ffb9b7104613cccccfea5315deeba03b247ac318"
      url "https://github.com/datamitsu/datamitsu/releases/download/v#{version}/datamitsu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d965041e4d744b403c90b42ba3de48c310b09336bfda82c7cc5c5892c7e257fc"
      url "https://github.com/datamitsu/datamitsu/releases/download/v#{version}/datamitsu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "datamitsu"
  desc "Configuration management and binary distribution tool."
  homepage "https://datamitsu.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "datamitsu"
  bash_completion "completions/datamitsu.bash"
  fish_completion "completions/datamitsu.fish"
  zsh_completion "completions/_datamitsu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/datamitsu"]
    end
  end

  # No zap stanza required

end
