# This file was generated by GoReleaser. DO NOT EDIT.
cask "datamitsu" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "e3c501d5a5a323cd24312e6170b052b2a2ad642693c8b85c078d087658f46dcc"
      url "https://github.com/datamitsu/datamitsu/releases/download/v#{version}/datamitsu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "da3a0277eba79d6400cf1f3d1232441b95c21cb95b749b0b01818f96e89273fa"
      url "https://github.com/datamitsu/datamitsu/releases/download/v#{version}/datamitsu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8b6aaffa56fdd155b1d2a7e6980f3ff5d0da9a473d323f2911014ac8ecf04ba6"
      url "https://github.com/datamitsu/datamitsu/releases/download/v#{version}/datamitsu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef28b8be60568be4c1321e630ffa399ee993fc613aeb64cbefd8b6afffa2052c"
      url "https://github.com/datamitsu/datamitsu/releases/download/v#{version}/datamitsu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "datamitsu"
  desc "Configuration management and binary distribution tool."
  homepage "https://datamitsu.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "datamitsu"
  generate_completions_from_executable "bin/datamitsu", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/datamitsu"]
    end
  end

  # No zap stanza required

end
