# This file was generated by GoReleaser. DO NOT EDIT.
cask "datamitsu" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "ac58070240c26677ff56417c74d26b17ab3a1b3dfb201e65903635f8d239a757"
      url "https://github.com/datamitsu/datamitsu/releases/download/v#{version}/datamitsu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5140398ea07fd8908182fcc63ea067a249aa35a2c5762d6da850234745c83d7a"
      url "https://github.com/datamitsu/datamitsu/releases/download/v#{version}/datamitsu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e11614520cef0e05bc1fb1876e79ca9e21008558444f753350e5e52150875ec6"
      url "https://github.com/datamitsu/datamitsu/releases/download/v#{version}/datamitsu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e214a5bff9575a1f9881f70e5d1e92de199b78c8bca0bf7d75b16b51853a3ea2"
      url "https://github.com/datamitsu/datamitsu/releases/download/v#{version}/datamitsu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "datamitsu"
  desc "Configuration management and binary distribution tool."
  homepage "https://datamitsu.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "datamitsu"
  bash_completion "completions/datamitsu.bash"
  fish_completion "completions/datamitsu.fish"
  zsh_completion "completions/_datamitsu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/datamitsu"]
    end
  end

  # No zap stanza required
end
